version: 0.2

phases: 
  install: 
    runtime-versions: 
      nodejs: 14.10.0
    commands:
      - npm install pm2@latest -g
  
  build: 
    commands: 
      - sudo rm -rf node_modules package-lock.json
      - npm install   
     
  post_build:
    commands:
      - pm2 start server.js
# artifacts:
#   files: 
#     - '**/*'