version: 0.2

phases: 
  install: 
    runtime-versions: 
      nodejs: 14.10.0
  
  build: 
    commands: 
      - npm install
     
  post_build:
    commands:
      - pm2 start server.js
# artifacts:
#   files: 
#     - '**/*'